# Small file to test if docker compose up works 
version: '3'
services:
  mongo:
    tty: false
    image: mongo:4.4.3-bionic
    container_name: mongo_container
    networks:
      clusternetwork:
        ipv4_address: ${MONGO_IP}

  knowrob:
    tty: true
    image: "knowrob/k4r"
    container_name: knowrob_container
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - 'mongo'
    environment:
      - KNOWROB_MONGODB_URI=mongodb://${MONGO_IP}:27017/?appname=knowrob
    networks:
      clusternetwork:
        ipv4_address: ${KNOWROB_IP}
    ports:
      - "62226:62226"
    entrypoint: /entrypoint.bash
    command: roslaunch knowrob_k4r knowrob_k4r.launch

networks:
  clusternetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}